### ISSUE TITLE
Some liveries are not visible by LM

### ISSUE THREAD

**Issue by JLD95** [RagingLightning/TSW3-LM#8]
**Describe the bug**
Some liveries in Lib dir are not listed
for example:
[https://www.trainsimcommunity.com/mods/c3-train-sim-world/c16-reskins/c83-british/c33-british-locomotives/i4054-142034-provincialnetwork-north-west](url)
[https://www.trainsimcommunity.com/mods/c3-train-sim-world/c16-reskins/c83-british/c33-british-locomotives/i4050-142009-old-gmpte-orange-brow](url)
[https://www.trainsimcommunity.com/mods/c3-train-sim-world/c16-reskins/c82-european/c81-european-rolling-stock/i3968-fex-livery-for-rpt-dosto-cab-car](url)

**To Reproduce**
1. Start LM
2. Left windows don't display these liveries
3.  See error in <TSW3LM.log> file

**Expected behavior**
display an error ?.

**Debug log**
+-------------------
+ Log file added on 0106T08:00:57.640 at level INFO
+-------------------
[INFO] 0106T08:00:57.642 MW:<init> | + Starting TSW3LM Version 1.0.0
[INFO] 0106T08:00:57.643 MW:<init> | Command line: TSW3LM.exe
[INFO] 0106T08:00:57.663 MW:<init> | Checking for updates...
[INFO] 0106T08:00:57.844 LI:Init | LiveryInfo initializing...
[INFO] 0106T08:00:57.845 LI:Load | Loading Livery info...
[INFO] 0106T08:00:57.859 MW::<init> | Loading GamePath Data...
[INFO] 0106T08:00:57.863 G:Load | Loading game liveries...
[WARNING] 0106T08:00:57.865 G:Load | No livery exists in the game...
[INFO] 0106T08:00:57.869 MW:UpdateGameGui | Updating game liveries in GUI...
[INFO] 0106T08:00:57.873 L:Load | Loading library...
**[WARNING] 0106T08:00:57.977 L:Load | Error while loading livery FEX RPT Cab Car for RF_DBpbzfa_767.tsw3!
[WARNING] 0106T08:00:57.978 L:Load | The method or operation is not implemented.**
   at GvasConverter.GvasJsonConverter.ReadUEEnumProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEGenericStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at TSW3LM.LibLivJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\repos\TSW3-LM\Utils.cs:line 526
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   **at TSW3LM.Library.Load() in D:\repos\TSW3-LM\Library.cs:line 16
[WARNING] 0106T08:00:58.073 L:Load | Error while loading livery FEX RPT Dostos for RF_DBpza_780.tsw3!
[WARNING] 0106T08:00:58.073 L:Load | The method or operation is not implemented.**
   at GvasConverter.GvasJsonConverter.ReadUEEnumProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEGenericStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at TSW3LM.LibLivJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\repos\TSW3-LM\Utils.cs:line 526
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at TSW3LM.Library.Load() in D:\repos\TSW3-LM\Library.cs:line 16
[INFO] 0106T08:00:58.079 MW:UpdateLibraryGui | Updating library liveries in GUI...

**Comment by JLD95** [comment]
C:\Utilitaires\TSW\TSW3 Livery-Manager>TSW3LM.exe -debug

C:\Utilitaires\TSW\TSW3 Livery-Manager>[INFO] 0106T08:09:48.765 MW:<init> | + Starting TSW3LM Version 1.0.0
[INFO] 0106T08:09:48.767 MW:<init> | Command line: TSW3LM.exe -debug
[DEBUG] 0106T08:09:48.768 Config:Save | Saving Config...
[DEBUG] 0106T08:09:48.787 Config:Save | Config saved
[INFO] 0106T08:09:48.788 MW:<init> | Checking for updates...
[INFO] 0106T08:09:48.968 LI:Init | LiveryInfo initializing...
[DEBUG] 0106T08:09:48.968 LI:Init | |> Path: F:\HDD_TSW4\Reskins_Livery Manager\zz_LiveryInfo.json
[INFO] 0106T08:09:48.969 LI:Load | Loading Livery info...
[DEBUG] 0106T08:09:48.982 LI:Load | Livery info loaded.
[INFO] 0106T08:09:48.983 MW::<init> | Loading GamePath Data...
[INFO] 0106T08:09:48.987 G:Load | Loading game liveries...
[DEBUG] 0106T08:09:48.987 G:Load | Deserializing Game Livery file...
[DEBUG] 0106T08:09:48.988 G:Load | File Path: C:\Users\Jean-Luc\OneDrive\Documents\My Games\TrainSimWorld4\Saved\SaveGames\UGCLiveries_0.sav
[DEBUG] 0106T08:09:48.989 G:Load | Game Livery file fully deserialized
[DEBUG] 0106T08:09:48.989 G:Load | Loading Liveries...
[WARNING] 0106T08:09:48.990 G:Load | No livery exists in the game...
[DEBUG] 0106T08:09:48.991 G:Load | All liveries loaded successfully
[INFO] 0106T08:09:48.994 MW:UpdateGameGui | Updating game liveries in GUI...
[DEBUG] 0106T08:09:48.996 MW:UpdateGameGui | Game liveries in GUI updated
[INFO] 0106T08:09:48.998 L:Load | Loading library...
[WARNING] 0106T08:09:49.108 L:Load | Error while loading livery FEX RPT Cab Car for RF_DBpbzfa_767.tsw3!
[WARNING] 0106T08:09:49.108 L:Load | The method or operation is not implemented.
   at GvasConverter.GvasJsonConverter.ReadUEEnumProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEGenericStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at TSW3LM.LibLivJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\repos\TSW3-LM\Utils.cs:line 526
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at TSW3LM.Library.Load() in D:\repos\TSW3-LM\Library.cs:line 16
[WARNING] 0106T08:09:49.195 L:Load | Error while loading livery FEX RPT Dostos for RF_DBpza_780.tsw3!
[WARNING] 0106T08:09:49.195 L:Load | The method or operation is not implemented.
   at GvasConverter.GvasJsonConverter.ReadUEEnumProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEGenericStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEStructProperty(JObject o)
   at GvasConverter.GvasJsonConverter.ReadUEProperty(JObject o)
   at TSW3LM.LibLivJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\repos\TSW3-LM\Utils.cs:line 526
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at TSW3LM.Library.Load() in D:\repos\TSW3-LM\Library.cs:line 16
[DEBUG] 0106T08:09:49.199 L:Load | Library fully loaded
[INFO] 0106T08:09:49.203 MW:UpdateLibraryGui | Updating library liveries in GUI...
[DEBUG] 0106T08:09:49.204 MW:UpdateLibraryGui | Added library livery RER Vaud for RABe523 <RER Vaud for RABe523.tsw3>
[DEBUG] 0106T08:09:49.204 MW:UpdateGameGui | Library liveries in GUI updated
[DEBUG] 0106T08:09:49.208 U:CheckUpdate | Got version information: 1.0.0->System.Net.Http.HttpConnectionResponseContent

**Comment by JLD95** [comment]
thank you very much, v1.1 works fine
